### ISSUE TITLE
[Front-end] Add back-to-top option in pages

### ISSUE THREAD

**Issue by overeha** [code4romania/ce-ma-fac#100]
Most of the pages are very long, please add a back to top option for the website

**Comment by aniri** [comment]
@DanielStoica85 the component was merged! are you still up for integrating it here? :smile:

**Comment by tudorgergely** [comment]
I can take this over if @DanielStoica85 doesn't have time for it :)

**Comment by DanielStoica85** [comment]
Sorry guys, I was really busy these past few days and I managed to miss @aniri 's message.

@tudorgergely , feel free to takeover.

**Comment by tudorgergely** [comment]
ok, I'm on it

**Comment by tudorgergely** [comment]
hey guys, BackToTop was not exported properly in taskforce-components so I couldn't use it. Opened this PR: https://github.com/code4romania/taskforce-fe-components/pull/133 which fixes the export issue.

Will finish this ticket once that is merged and republished.

**Comment by aniri** [comment]
@tudorgergely the 1.0.7 version of the components is live! :rocket:

**Comment by tudorgergely** [comment]
@aniri thanks! PR opened
