### ISSUE TITLE
Create Afla mai multe section for content pages

### ISSUE THREAD

**Issue by aniri** [code4romania/ce-ma-fac#112]
long story short: unele dintre paginile de continut simplu (nu cele gen ai simptome) vor fi alcatuite din subpagini si apare meniul din sidebar (care are doar varianta unfolded). cand dai click de sus pe una din pagini, iti apare la content doar prima subpagina (daca are subpagini) sau toata pagina (daca nu are subpagini) **si apare si bucata cu "afla mai multe" daca mai are si alte subpagini.**

Figma here: https://www.figma.com/proto/XDcxBzr6MdMlrZmmlBTYvu/Content-design---CeMaFac?node-id=1%3A214&scaling=min-zoom

**Comment by bogdan00** [comment]
am sa incerc sa abordez acest issue :)
