### ISSUE TITLE
[frontend] Change buttons display for assesment form

### ISSUE THREAD

**Issue by overeha** [code4romania/ce-ma-fac#127]
Right now the two buttons used to navigate through the self assessment form are displayed one under the other on mobile. We need them to be inline. 

![Screenshot_20200323-170603](https://user-images.githubusercontent.com/45068169/77333430-15cd8300-6d2c-11ea-87f6-62907df2630c.jpg)

**Comment by movileanubeniamin** [comment]
They already are in the same line.
![image](https://user-images.githubusercontent.com/13012677/77816638-dfe22300-70cc-11ea-8c04-3bef55109e60.png)

**Comment by aniri** [comment]
@movileanubeniamin thanks for checking! I will close this issue as it seems it was fixed already.
