### ISSUE TITLE
Add new content page - myths

### ISSUE THREAD

**Issue by overeha** [code4romania/ce-ma-fac#149]
Add a new content page called ”Mituri despre coronavirus”

- [ ] list & format the information from here

https://docs.google.com/spreadsheets/d/1MPtwc03rTIWn1MguuFQPOrm1jhO-j_kd7rX7E3fd96g/edit?usp=sharing

- [ ] Every line in the excel file has an associated image. Images are here: https://drive.google.com/open?id=1S6Q2hw3cJbwbYqYuD8c3sj5bL0-fFrgR

**Comment by aniri** [comment]
Content for pages is defined in json files, please check https://github.com/code4romania/ce-ma-fac/blob/develop/frontend/src/data/static-pages.js

**Comment by VeronicaM** [comment]
Buna, voi lucra pe acest issue 👍
