### ISSUE TITLE
Open links in new tab in order not to loose the current page

### ISSUE THREAD

**Issue by codrutas1** [code4romania/ce-ma-fac#154]
In some pages (e.g.  https://test.cemafac.ro/ > Transmitere și simptome) there are links in page  (e.g. Știri oficiale ). When clicked, the user is redirected to the target page and has to press back in browser to return to the original page.
It would be nice to open the target page in a new tab, so that the user doesn't lose the main page.

**Comment by bianca-gauca** [comment]
I can take it :)

**Comment by moonflare** [comment]
Hey @codrutas1 👋 I did a quick check and it seems we do have target blank on all the links. Can you please double check?

**Comment by aniri** [comment]
@moonflare the links from the content for `Transmitere și simptome` available in json, do not have target blank.

**Comment by aniri** [comment]
@bianca-gauca the content of the pages, is set here: https://github.com/code4romania/ce-ma-fac/blob/develop/frontend/src/data/static-pages.js

**Comment by moonflare** [comment]
> @moonflare the links from the content for `Transmitere și simptome` available in json, do not have target blank.

Ah ok. Thanks for clarifying

**Comment by codrutas1** [comment]
M-am uitat prin pagini si cam astea ar fi cazurile de linkuri care se deschid in acelasi tab. Pe langa cele date in bug am mai gasit 2 cazuri.


Links that redirect to same page instead of a new tab:

Page: Transmitere și simptome (https://ce-ma-fac.now.sh/)
Section: Situatia din Romania
Links: "Știri oficiale", "Zone internaționale afectate", "Site Institutului Național de Sănătate Publică"

Page: https://ce-ma-fac.now.sh/adaptare-si-rezistenta/sfaturi-pentru-parinti
Section: "Sunt multe lucruri pe care le poti face pentru a-ti sustine copilul:"
Link: "despre COVID-19"

Page: https://test.cemafac.ro/intrebari-frecvente
Section: "Există cazuri în România?"
Link: "Numărul oficial de infecții poate fi văzut <link>aici</link>"

**Comment by codrutas1** [comment]
Works fine on https://ce-ma-fac.now.sh/ - PC (Chrome, FF, Edge), Galaxy S5 - Android (Chome, FF, default browser)
