### ISSUE TITLE
Add visual indicator on mobile for the text that support direct call & sending emails

### ISSUE THREAD

**Issue by codrutas1** [code4romania/ce-ma-fac#155]
There are pages (e.g. https://test.cemafac.ro/pentru-cei-care-ofera-ajutor ) that contain phone numbers or email addresses.
E.g.  "Cum puteți beneficia de ajutor:
0758 119 314
consiliere@estuar.org"
On mobile, when the user presses on the phone number or email (s)he can make a direct call or send an email.
Still, there is no visual indicator in UI for the user that an action is supported

![Phone Number and email](https://user-images.githubusercontent.com/6797637/77821403-b3410200-70f2-11ea-9e14-0ae9c749d87d.png)

**Comment by redecs** [comment]
Checked the page referenced in the issue and in iOS / Safari you can't click phone numbers or emails to perform action. Maybe on Android they behave differently.
A quick solution that provide consistency cross-platform (and partially works on desktop) is to use `a href=tel:` and `a href=mailto:`, visually those will become links (optionally we could add some icons if the style-guide / branding allows it).
As this is a first good issue, I could do the changes if you confirm this a good course of action.

**Comment by zauan** [comment]
Vizual se vede asa cu implementarea propus... eu zic ca e ok ca si implementare:
![image](https://user-images.githubusercontent.com/5928748/77823707-c1e4e480-7105-11ea-82c4-8126aff43bee.png)

**Comment by codrutas1** [comment]
Buna, am reusit sa ma uit prin toate paginile si am centralizat locurile in care apar numere de telefon. Situatia pusa in bugul original apare si ea in lista.

Phone numbers:

Page: Transmitere și simptome (https://test.cemafac.ro/)
Section:"Dacă ai simptome, sau dacă ai nevoie de informații" (bottom of the page)
Text: "TelVerde la numărul 0800.800.358", "linia special dedicată lor +4021.320.20.20."

Page: https://test.cemafac.ro/cum-ne-protejam/plan-actiune-acasa
Text: "TelVerde 0800 800 358"

Page: https://test.cemafac.ro/pentru-cei-care-ofera-ajutor
Section: "Fundatia Estuar a lansat 4medicALL...."
Text: "Cum puteți beneficia de ajutor:
0758 119 314
0758 119 313
0758 119 304"

Page: https://test.cemafac.ro/intrebari-frecvente
Section: Ce să fac dacă am avut contact direct cu o persoană confirmată cu COVID-19?
Text: "Contactați autoritățile la linia TELVERDE 0800 800 358"

Page: https://test.cemafac.ro/intrebari-frecvente
Section: Ce pot face persoanele ce prezintă risc ridicat de îmbolnăvire?
Text: "contactați 112"

**Comment by redecs** [comment]
@codrutas1 tocmai am facut un pull-request in care am mdoficiat numerele de telefon pe care le-am gasit.
Am ratat cateva numere de telefon. O sa fac o cautare mai atenta, aparent sunt mai multe refereinte catre numarul TelVerde.

O singura mentiune: n-as pune link si pe 112. E numar de urgenta, poate fi format foarte usor si ma indoiesc ca daca cineva are o urgenta va citit textele de pe site si ii va fi utila acea scurtatura.

**Comment by codrutas1** [comment]
Sounds fair.
I defined a separate issue for the remaining phone numbers found: https://github.com/code4romania/ce-ma-fac/issues/163

**Comment by redecs** [comment]
@codrutas1 thanks! 
New pull request made with additional links.
