### ISSUE TITLE
Unclear message when pressing submit without choosing unsubscribe message

### ISSUE THREAD

**Issue by codrutas1** [code4romania/ce-ma-fac#158]
1. Subscribe to the application:
https://ce-ma-fac.now.sh/ -> "Rămai informat" section enter a valid email address end press submit
2. Check the received email and confirm to be submitted to the list
3. In "Subscription Confirmed" page click "Manage your preferences"
4.  In "Update your preferences" page click  "Email Me a link"
5. In the received email click "Update your preferences" link
6. In "Rămâi informat despre ecosistemul....." page click  Unsubscribe link
7. In "Unsubscribe" page enter your email address and click Unsubscribe
8. In "Unsubscribe Successful" page click Submit without choosing any reason.

Expected Result:
The validation message should indicate that the user should choose a reason
Actual result:
The validation message is vague "There were errors recording your feedback, please try again later"
and doesn't make clear which is the problem.

Note: shouldn't the user receive a confirmation mail: "You was unsubscribed...."?
![1Ramai Informat](https://user-images.githubusercontent.com/6797637/77823730-f9539100-7105-11ea-8811-9bf4e83eb89a.jpg)
![2Message when option isn't selected](https://user-images.githubusercontent.com/6797637/77823732-fd7fae80-7105-11ea-8bf7-efa492c48306.jpg)

**Comment by cosmin-bianu** [comment]
Is anyone handling it? I'd like to look into it

**Comment by GabrielMajeri** [comment]
It looks like this issue can only be solved by whoever has access to the MailChimp account for the mailing list
