### ISSUE TITLE
Add autoscroll to content after clicking a sidebar link

### ISSUE THREAD

**Issue by stevefai** [code4romania/ce-ma-fac#159]
On mobile devices, the sidebar navigation menu (`Navigare Rapida`) takes the whole height of the screen. When clicking a link, the user has the feeling that nothing happens, because the content is displayed well below the sidebar. 

In order to fix this, we should autoscroll to the beginning of the related section.
  

![sidebar](https://user-images.githubusercontent.com/10120263/77824412-25bddc00-710b-11ea-806f-ec563c23ce90.png)

**Comment by bogdan00** [comment]
pot sa ma ocup de asta
