### ISSUE TITLE
[Mobile]User can select multiple options in Navigare rapida menu

### ISSUE THREAD

**Issue by anav238** [code4romania/ce-ma-fac#160]
Steps to reproduce:
1. Access https://ce-ma-fac.now.sh/ from your phone and scroll down to Navigare rapida menu.
2. Select an option from the menu.
3. Long press another option from the menu.

Expected result: only the last option tapped should appear selected.

Actual result: the last option tapped appears selected, along with another option that was tapped previously.
 
![image](https://user-images.githubusercontent.com/45420849/77824370-e2636d80-710a-11ea-9f1a-0457271a3ca3.png)

**Comment by zauan** [comment]
O sa ma ocup eu de tichetul asta :)

**Comment by zauan** [comment]
Am bagat un fix in https://github.com/code4romania/taskforce-fe-components/pull/124 .

Daca totul e ok, ar trebui facut release nou la @code4ro/taskforce-fe-components, update package.json din proiectul curent si npm update pentru a trage modificarile

Unii pasi nu ii pot face eu pentru ca nu am acces asa ca va rog sa nu inchideti tichetul pana nu e integrat totul.
