### ISSUE TITLE
Open links in new tab in order not to loose the current page (2)

### ISSUE THREAD

**Issue by codrutas1** [code4romania/ce-ma-fac#162]
In some pages there are links. When clicked, the user is redirected to the target page and has to press back in browser to return to the original page.
It would be nice to open the target page in a new tab, so that the user doesn't lose the main page.

Page: https://ce-ma-fac.now.sh/adaptare-si-rezistenta/sfaturi-pentru-parinti
Section: "Sunt multe lucruri pe care le poti face pentru a-ti sustine copilul:"
Link: "despre COVID-19"

Page: https://test.cemafac.ro/intrebari-frecvente
Section: "Există cazuri în România?"
Link: "Numărul oficial de infecții poate fi văzut <link>aici</link>"

**Comment by aniri** [comment]
this was fixed

**Comment by codrutas1** [comment]
Page: https://test.cemafac.ro/intrebari-frecvente
Section: "Există cazuri în România?"
Link: "Numărul oficial de infecții poate fi văzut aici"

still opens in the same page
