### ISSUE TITLE
Incorrect display of the questions when having "COVID-19" extension enabled

### ISSUE THREAD

**Issue by codrutas1** [code4romania/ce-ma-fac#167]
When opening https://ce-ma-fac-j8gecy4sk.now.sh/mituri-despre-coronavirus page in Firefox (with COVID-19 ȘTIRI OFICIALE extension enabled) the names of the questions are not properly aligned.
![Miths - alignment Firefox](https://user-images.githubusercontent.com/6797637/77828760-1435fd80-7126-11ea-8e45-a28f302bfe0f.png)

After disabling the extension, the names look fine

This happens on both Chrome and Firefox

**Comment by bogdan00** [comment]
ma uit la asta

**Comment by bogdan00** [comment]
seems fixed here: https://ce-ma-fac-git-fork-veronicam-feature-149-new-content-page.code4ro.now.sh/mituri-despre-coronavirus , PR #166  needs merging

**Comment by codrutas1** [comment]
Hi,
In https://ce-ma-fac-git-fork-veronicam-feature-149-new-content-page.code4ro.now.sh/mituri-despre-coronavirus the icons look as below:
![Myths - icons on Galaxy S5](https://user-images.githubusercontent.com/6797637/77858235-d232b780-720a-11ea-8f20-7a5d8e04f0ce.png)
The icons here (https://emojipedia.org/keycap-digit-one/ ) have the same display problem as in Myths page.

**Comment by codrutas1** [comment]
https://ce-ma-fac-git-fork-veronicam-feature-149-new-content-page.code4ro.now.sh/mituri-despre-coronavirus - the alignment is ok now,  please see below the aspect for Firefox (on Chrome it's similar)
![PC - firefox](https://user-images.githubusercontent.com/6797637/77858598-2d65a980-720d-11ea-8fcb-80bebd2731fe.jpg)

**Comment by aniri** [comment]
this was fixed :D
