### ISSUE TITLE
Some icons in Myths page are not properly displayed on mobile

### ISSUE THREAD

**Issue by codrutas1** [code4romania/ce-ma-fac#168]
1. On mobile open https://ce-ma-fac-j8gecy4sk.now.sh/mituri-despre-coronavirus
2. Expand "Pot fi infectat cu coronavirus chiar dacă nu am simptome?" section
3. Check how the "number icons" are displayed.

Expected Result:
The "number icons" should be properly displayed.

Actual Results:
On my Samsung Galaxy S5 (Android 6.0.1) the icons are not properly displayed:

Chrome:

![Myths - mobile icons Chrome](https://user-images.githubusercontent.com/6797637/77830319-56fcd300-7130-11ea-81ca-6820da26d699.png)

Firefox
![Myths - mobile icons Firefox](https://user-images.githubusercontent.com/6797637/77830327-624ffe80-7130-11ea-9de9-1bc0af9e5bae.png)

**Comment by redecs** [comment]
On iOS/Safari looks ok. I suspect that there is a specific problem with the char code for that emoji (keycap numbers) on that platform (in theory it should work on Android 6.0, maybe it's something Samsung did).

@codrutas1 can you please visit this page and tell me if you see the emojis displayed correctly?

**Comment by codrutas1** [comment]
I'm not sure what "This page" means :) but it's very probable to be related to my phone (either Android 6, or both OS & Samsung Galaxy S5 combination. I don't see properly the icons in the document (https://docs.google.com/spreadsheets/d/1MPtwc03rTIWn1MguuFQPOrm1jhO-j_kd7rX7E3fd96g/edit#gid=1959070011), either.
![Android 6](https://user-images.githubusercontent.com/6797637/77835511-0a2bf300-7156-11ea-9a65-e91279096519.png)

**Comment by redecs** [comment]
@codrutas1 sorry, it was late I forgot to put in the link: https://emojipedia.org/keycap-digit-one/ :)
are these displayed correctly? It might be a problem with your device, but on the otherside Samsung makes a LOT of devices and that could mean that a lot of people might have the same issue :one: :two:

**Comment by aniri** [comment]
hey @redecs @codrutas1  :) I think there is already a fix for this issue here: https://ce-ma-fac-at4h6gjf1.now.sh/mituri-despre-coronavirus ; implemented in PR https://github.com/code4romania/ce-ma-fac/pull/166

**Comment by redecs** [comment]
@aniri awesome! it was a tricky one to reproduce anyway.

**Comment by codrutas1** [comment]
Hi, firefox is the winner :)) 
![Myths - icons on Galaxy S5](https://user-images.githubusercontent.com/6797637/77858824-93066580-720e-11ea-9bd4-cad0a88c2f81.png)

You should try to display the page on a different android phone, there are good chances to be very specific.
On Chrome and Samsung's default browser the icons here (https://emojipedia.org/keycap-digit-one/) have the same display problem.
