### ISSUE TITLE
Header logos are too big on mobile

### ISSUE THREAD

**Issue by cipick** [code4romania/ce-ma-fac#179]
![Screenshot_20200407-101905_Chrome](https://user-images.githubusercontent.com/6429818/78641235-9908e000-78b9-11ea-9c1a-809754e70c4d.jpg)

I can take this issue since the bug was introduced by a PR created by me :( https://github.com/code4romania/ce-ma-fac/pull/177

**Comment by aniri** [comment]
Please check if it would be best to improve the developedby component from https://github.com/code4romania/taskforce-fe-components for sizing the logos :) So all the projects that use it will be improved :)

**Comment by danichim** [comment]
This issue is only on the development environment, on production looks good. 
![image](https://user-images.githubusercontent.com/14906788/78873445-90e4a800-7a53-11ea-97ef-cce43a17892c.png) @cipick @aniri

**Comment by aniri** [comment]
@danichim yes, the logos displayed was changed in the dev environment. and will soon also be updated in prod. this issue is related to what we now have in dev :)

**Comment by danichim** [comment]
ok, so i can take it to fix ?

**Comment by cipick** [comment]
@aniri so sorry for the delay i have created a PR for https://github.com/code4romania/taskforce-fe-components to resize the logos on mobile https://github.com/code4romania/taskforce-fe-components/pull/148
