### ISSUE TITLE
Missing role link for https://www.aadr.ro

### ISSUE THREAD

**Issue by DragomirStefanaCatalina** [code4romania/ce-ma-fac#205]
Starting point: https://cetrebuiesafac.ro

**Expected**:
Click on role img Autoritatea pentru digitalizarea României
Autoritatea pentru digitalizarea României site opens https://www.aadr.ro

**Actual**:
Click on role img Autoritatea pentru digitalizarea României
Guvernul României site opens https://www.gov.ro

![Screenshot 2020-04-25 at 12 43 36](https://user-images.githubusercontent.com/61550276/80276596-803e5e00-86f2-11ea-81a2-0a68134b66bb.png)

**Comment by aniri** [comment]
That is a joint logo ;) As it was received from Gov. They are not separate images :smile:

**Comment by RaduCStefanescu** [comment]
Then we should close this one. Thank you @aniri for clearing things up and @DragomirStefanaCatalina for logging the issue.
