### ISSUE TITLE
Repeated submenus for "Cum ne protejam?"

### ISSUE THREAD

**Issue by DragomirStefanaCatalina** [code4romania/ce-ma-fac#206]
Starting point: https://cetrebuiesafac.ro/cum-ne-protejam

**Expected**:
5 submenus
![Screenshot 2020-04-25 at 12 50 03](https://user-images.githubusercontent.com/61550276/80276759-62252d80-86f3-11ea-8087-672799063ee2.png)

**Actual**:
Repeated submenus 

![Screenshot 2020-04-25 at 12 47 41](https://user-images.githubusercontent.com/61550276/80276727-3144f880-86f3-11ea-8e43-f307c22139dc.png)

**Comment by danmana** [comment]
I can take this
