### ISSUE TITLE
Highlight sidebar menu entry

### ISSUE THREAD

**Issue by aniri** [code4romania/ce-ma-fac#221]
`Model declarație pe proprie răspundere` should be highlighted in the sidebar menu, it should have yellow background (use the yellow from the logo).

depends on https://github.com/code4romania/taskforce-fe-components/issues/191

**Comment by aniri** [comment]
in progress @cipick 

components version 1.0.27 was released :rocket:

**Comment by cipick** [comment]
I'm on it, thanks 😁
