### ISSUE TITLE
[Frontend] Implement sidebar search

### ISSUE THREAD

**Issue by aniri** [code4romania/ce-ma-fac#23]
Add the search box in the sidebar. 

The search will look for the keyword in the title and content text of the pages stored in the json file https://github.com/code4romania/ce-ma-fac/blob/develop/frontend/src/data/static-pages.js. 

The search input component should be imported from https://taskforce-fe-components.now.sh/?path=/story/search-input--search-input

Depends of this task for search results list https://github.com/code4romania/taskforce-fe-components/issues/107

Search results should include:
- page title
- short text
- citeste mai mult link

**Comment by stevefai** [comment]
Salut! As vrea sa iau eu asta.

**Comment by aniri** [comment]
@stevefai awesome! just note that the ui component for the search results cards is still in progress here: https://github.com/code4romania/taskforce-fe-components/issues/107

**Comment by stevefai** [comment]
Incep lucrul si folosesc un placeholder pana e gata componenta reutilizabila.

**Comment by aniri** [comment]
> Incep lucrul si folosesc un placeholder pana e gata componenta reutilizabila.

perfect!
